# Generated by Django 3.0.3 on 2020-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('file_image', models.TextField()),
                ('name_image', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
    ]
