# Generated by Django 3.0.3 on 2020-02-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id_dict', models.AutoField(primary_key=True, serialize=False)),
                ('title_dict', models.CharField(blank=True, max_length=100, null=True)),
                ('alpha', models.CharField(blank=True, max_length=2, null=True)),
                ('content_dict', models.TextField()),
            ],
            options={
                'db_table': 'dictionary',
                'managed': False,
            },
        ),
    ]
