# Generated by Django 3.0.3 on 2020-02-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('title_genre', models.CharField(blank=True, max_length=45, null=True)),
                ('content_genre', models.TextField()),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
    ]
